version: "3.4"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      target: development-stage
    entrypoint: sh -c "rm -f tmp/pids/backend.pid && bundle exec rails server -p 3000 -b '0.0.0.0' --pid tmp/pids/backend.pid"
    ports:
      - "3000:3000"
    env_file: .development.env.docker
    depends_on:
      - db
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 5
