default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_sut: &sut
  <<: *default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: backend_challenge_development

test:
  <<: *sut
  database: db/test.sqlite3

production:
  <<: *default
  database: backend_challenge_production
  username: backend_challenge
  password: <%= ENV['BACKEND_CHALLENGE_DATABASE_PASSWORD'] %>
